### ISSUE TITLE
"Copy and Paste" Equipment Lists

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#104]
My idea for allowing us to transfer equipment from one session to another, or to duplicate class setups. I think saving the equipment in the checkout list to the computer's clipboard, and allowing it to be pasted into the omnibox of another form, would be a good way to simplify checkouts that use the same equipment.

**Comment by dwmorrin** [comment]
Ok, let me know what API you are going to try.

Since the user is just repeating data we already have, as opposed to generating freewheeling data (like composing an email - as another copy/paste use case), you may be able to bypass security restrictions, browser compatibility and other headaches by just writing plain JavaScript to do a custom copy/paste from the old form to the new form via user inputs like checkboxes (for multiple selection) and buttons, and custom keyboard shortcuts.

**Comment by dwmorrin** [comment]
This is very similar to issue #30 if not the exact same issue with a specific implementation suggestion.

**Comment by michaelphagen** [comment]
I've put my in progress code on branch feat/clipboard with the commit 451ea35

**Comment by michaelphagen** [comment]
this is working on both safari and chrome. I'll see if i can get it to verify items against cache and clean it up.

**Comment by dwmorrin** [comment]
Summarizing some thoughts I had from reviewing the code:
* copy button should only be accessible from the closed forms section
* keep the copy utility sparse.  Just do the minimum (no `try` or calls to display functions).  [This looks like a good example.](https://techoverflow.net/2018/03/30/copying-strings-to-the-clipboard-using-pure-javascript/) I would even try and see if we can get away with `display: none` rather than the shown positioning trick.
