### ISSUE TITLE
Check in items with a quantity > 1

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#107]
We should either allow the user to check in _some_ of the items when multiple of the same item are checked out, or we should fix the bug that prevents the user from checking out an item again after checking it in. Ideally we will do both.

**Comment by dwmorrin** [comment]
So I guess we have to launch a modal whenever a quantity > 1 check in happens?

**Comment by michaelphagen** [comment]
I like that, but I'm not sure I understand what you mean by 
> Maybe number for check in is a drop down?

Do you mean within the check in modal the quantity selection would be a drop down? In that case, perhaps instead of a quick button for all we would just have the drop down default to the checked-out quantity.

**Comment by dwmorrin** [comment]
I'm looking at putting the drop down in the item list, next to the "Check In" button.  It appears if the quantity is > 1.  Looking good so far.

**Comment by dwmorrin** [comment]
The current solution loses information, or at least makes it difficult to retrieve.

### Current behavior
When you view a closed form that had partial returns, you will only see the last quantity, so if the max quantity was 10, but they returned 9, and then finally 1, the closed form will only show quantity.

### Expected behavior
I would like to see the max quantity that was every checked out shown in the closed forms.

### ideas
* closed forms calculate the max by parsing the change log
* could add a max quantity property to Items

**Comment by dwmorrin** [comment]
Issue was fixed with updated Item model.
