### ISSUE TITLE
Advance Bookings are not being pulled from RMSS

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#125]
Neither of the advance booked sessions for today were pulled into the forms spreadsheet. I can see them in the "Daily Booking Data" spreadsheet that has been used to print the forms, but I don't know how they should be automatically getting from that spreadsheet into the forms spreadsheet.

**Comment by michaelphagen** [comment]
Today, there were two advance forms for the 3:30pm session in Studio 510 in the open forms view. Looking at the forms spreadsheet, there were two entries for the same form, one that was "written by David" at 6:13am, and another that was added at 8:10am. I removed the one added at 8:10.

**Comment by dwmorrin** [comment]
The sessions not showing up was due to a mismatch on a student's name in the roster.  RMSS had a name update that did not go over to the "Students" form.

The duplicate the next day was trash from me testing the script.  You can ignore that one.

As to the issue, it is a roster update issue.

As far as the scope of this GitHub repo is concerned, this is a particular implementation detail that is beyond the scope of gas-eco, so I am closing this issue, but we can still work on it in a different context.
