### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#127]
Is this something that's possible with GAS, or are the cookies registered as *.google.com and therefore inaccessible?

Researching now.

**Comment by dwmorrin** [comment]
Can you add context as to where this is coming from?  At what point is the user going to need to hit a logout button?

In order to use this app, they have to be logged into the appropriate G Suite account, which extends beyond the scope of our app.

If you are wanting to implement a logout button that logs them out of their G Suite account, I think we would be reinventing the wheel.  Users should log out of the browser (if they are not using some kind of incognito or private mode) and close all windows (or "Quit" on MacOS) to "logout".

**Comment by michaelphagen** [comment]
Requested by Doug, I was curious as to whether it is possible to sign out 
front a gsuite account from within the app. Not an issue if not possible, 
as I always recommend using incognito mode.
________________________________

Michael Hagen
Recorded Music Technician

Clive Davis Institute of Recorded Music
Tisch School of the Arts
New York University
194 Mercer St, #517
New York, NY 10012
914-299-3142
