### ISSUE TITLE
Lost location info

### ISSUE THREAD

**Issue by dwmorrin** [dwmorrin/gas-eco#13]
To reproduce: 
I am currently on dev/michael.
I opened up a form, checked a student in, checked out a manual item, saved, went to open forms, checked out another form, came back to first form and location was gone; blanked out in Forms sheet.

**Comment by michaelphagen** [comment]
I believe that the origin of this issue is in the operation of the "other" location tag. the modal window accepts a blank string as an input, and then will accept a blank location thereafter

**Comment by michaelphagen** [comment]
The fix on hotfix/13 separates the "other" option in the drop down from the option that is displayed after setting a custom location. The Process is as follows:
The user clicks on "other" in the location drop down (which has the value "OtherSelector").
The "other location" modal window opens and the user enters an "other" location name.
The input name is then set as the name of the "" option (which has the value "other"), and is un-hidden.
the form can then be saved with the new location.

If/when the user opens the location drop down again:
The "" option (value "other") is set to hidden again (because otherwise this persists between forms)
The user can select one of the standard locations, or select the "Other" value (value 'otherSelector') which will bring up the "Other Location" modal and start the process again


In addition, if when prompted for the "other" location title in the "other location" modal, the user enters nothing and tries to continue, the modal will simply be re-opened.

**Comment by michaelphagen** [comment]
I've still seen this a few times today on branches stemming from master (hotfix/collisions and hotfix/13-1). I haven't been able to track down a specific cause yet. It happened once after a collision on hotfix/collisions and another time after changing the location to an "other" location on one form and then changing to another form and changing the location to an "other" location.

**Comment by dwmorrin** [comment]
Steps to reproduce on hotfix/13-1?
I haven't been able to yet.
feat/collision does not have the location fix.

**Comment by michaelphagen** [comment]
### Steps to reproduce location loss on hotfix/13-1

1. Open a saved form
2. Click the location drop down and select other
3. In the modal window that opens type nothing and click "set location"
4. save the form

The form will now have no location.

### Proposed Fix
check in DoCommand.html::setLocationOther if the value from the modal is blank, and if so, open the modal again without proceeding.

```
if (otherLocation == ''){
        app.modal.getLocation();
        break;
      }
```
This could be inserted after the variable declarations in DoCommand.html::setLocationOther.

**Comment by michaelphagen** [comment]
I'm coming back from lunch now, but I have yet to find a reproduceable way 
to make it oose the location. I'm thinking it could be something in the 
refresh but i'm going to need to look again when I get back.
________________________________

Michael Hagen
Recorded Music Technician

Clive Davis Institute of Recorded Music
Tisch School of the Arts
New York University
194 Mercer St, #517
New York, NY 10012
914-299-3142
