### ISSUE TITLE
Add sorting to Archive

### ISSUE THREAD

**Issue by michaelphagen** [dwmorrin/gas-eco#44]
Requested by Michael McCoy. He asked that the archive view allow form sorting in the same way that the open forms view does

**Comment by dwmorrin** [comment]
Let's factor out the two big `switch` blocks that figure out what to compare by into it's own function.  Both views should be able to use the same function.  At some point we may allow user preferences to view the open forms as wide as the closed forms, so it makes sense to allow sorting on either view on all the possible columns.

**Comment by dwmorrin** [comment]
I starting going down this road again when I noticed `displayOpenForms` had been orphaned.
I'm just jotting down my thoughts here before a lunch break.

### Current behavior
Viewing open forms (probably archive as well?) always results in the same default sort.

### Expected behavior
App should remember your last sort setting (at least within a single session; we can look into user properties for persistent settings).

The properties `app.pages.<pagename>.sortBy` were added to the archive and openForms pages long ago to make this possible, but they do not appear to be utilized correctly at the moment.

Next steps:
* `utility.sortForms` references these properties right off the bat but it appears confused as to whether it is looking at archive or openForms.  First we should establish the context, which leads to...
* review our current context checking methods and apply the same method everywhere; even better make it a utility function, e.g. `utility.getContext()` that returns a string e.g. `openForms`
* check everywhere that uses `utility.sortForms`, e.g. doCommand case "sortForms", which currently do not set the page property, but should.

**Comment by dwmorrin** [comment]
see issue #20 for context info
`app.cache.currentFormstack` is how we track the context

**Comment by dwmorrin** [comment]
For the archive:

Clicking on the "closed forms" button runs the `show` function for the page, which will either run `.update()` or `.query()` on `app.pages.archive`.  Either option needs to respect the value of `.sortBy`.

**Comment by dwmorrin** [comment]
Found a bug.  `.query` ends in a `populate` function... and so does `.refresh`
So the code has been double populating.
Part of this stems from `.query` just being to big.
New TODO:
1. factor `.query`
2. `.query` should return a filtered array.
