### ISSUE TITLE
Double scanning non serialized items does not prompt for quantity

### ISSUE THREAD

**Issue by dwmorrin** [dwmorrin/gas-eco#56]
### Current behavior
Scanning non serialized item (tried 10002 generic power strip) twice does nothing.

### Expected behavior
Scanning non serialized item twice prompts for quantity

**Comment by dwmorrin** [comment]
See js/Logic function isCheckInItemOk

**Comment by michaelphagen** [comment]
Closed with 336baf9

**Comment by dwmorrin** [comment]
### Current behavior
The check-in button, if clicked without updating form, opens the change quantity dialog.

From the system design point of view, this is what we want.

However, from the user's point of view, it's weird.

### Suggested change
Disable the check-in button until the form has been saved

**Comment by michaelphagen** [comment]
The fix currently in hotfix/56 makes it so that clicking the non-serialzied/manual item check-in buttons without first saving the item into the form will throw the same error as attempting to check-in a serialized item without first saving it into the form.

I've also refactored the manual entry button to use it's own doCommand case, because otherwise the if statement checking if the clicked target has the dataset "itemid" would be true for both the manual entry buttons and for the check-in buttons. This is a cleaner way to do this anyway, since the barcode for manual entry doesn't change depending on the item.
